version:  '3.7'
services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: password
  adminer:
    image: adminer
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - 8101:8080
  nginx:
    image: nginx
    ports:
      - 8100:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - php:/var/www/html
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - php:/var/www/html
    depends_on:
      - mysql

volumes:
  php:
    driver_opts:
      type: none
      device: ${PWD}
      o: bind